name: pocket_planner
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  get: ^4.6.5
  go_router: ^6.0.3
  freezed_annotation: ^2.0.3
  pin_code_fields: ^7.4.0
  lottie: ^2.2.0
  flutter_svg: ^2.0.0+1
  cached_network_image: ^3.2.3
  percent_indicator: ^4.2.2
  modal_bottom_sheet: ^3.0.0-pre
  google_sign_in: ^6.0.0
  firebase_auth: ^4.2.8
  firebase_core: ^2.6.1
  flutter_facebook_auth: ^5.0.7
  translator: ^0.1.7
  dio: ^5.0.0
  shared_preferences: ^2.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^2.0.3+1
  json_serializable: ^6.1.3

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/lottie_animation/
    - assets/images/