// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmNJri4nB43Vwd2ugf5hGGAlkg4j1GwLw',
    appId: '1:952229417862:web:b2b9e7899cb75423c71207',
    messagingSenderId: '952229417862',
    projectId: 'totaplanpro',
    authDomain: 'totaplanpro.firebaseapp.com',
    storageBucket: 'totaplanpro.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGcrkbDefEifMm_31LAErBXpP07otPgX0',
    appId: '1:952229417862:android:09b9205c9bc128c0c71207',
    messagingSenderId: '952229417862',
    projectId: 'totaplanpro',
    storageBucket: 'totaplanpro.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDf3rqTH08rOAPgoYbb6_7d--rWez_p1mc',
    appId: '1:952229417862:ios:5fc085bbd829d8a2c71207',
    messagingSenderId: '952229417862',
    projectId: 'totaplanpro',
    storageBucket: 'totaplanpro.appspot.com',
    iosClientId: '952229417862-rcmunnt8hlvdsn6tghufldredrtictc0.apps.googleusercontent.com',
    iosBundleId: 'com.app.plannerpro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDf3rqTH08rOAPgoYbb6_7d--rWez_p1mc',
    appId: '1:952229417862:ios:e7d0fcad733cedbec71207',
    messagingSenderId: '952229417862',
    projectId: 'totaplanpro',
    storageBucket: 'totaplanpro.appspot.com',
    iosClientId: '952229417862-k85dfbeb31st79alsmal0vemh0gfg9nb.apps.googleusercontent.com',
    iosBundleId: 'com.pocketPlanner',
  );
}
